# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
r:
  - release
  - devel

before_install:
  - sudo $(which R) CMD javareconf
  - sudo apt-get install -y libsndfile1-dev
  - sudo apt-get install -y libfftw3-dev
env:
  global:
    - _R_CHECK_SYSTEM_CLOCK_=0
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran rpack"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual rpack"
